# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build And Push Gateway

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Change Directory
        run: cd gateway && pwd
      - name: Grant execute permission for gradlew
        run: chmod +x gateway/gradlew
      - name: Build with Gradle
        run: gateway/gradlew build

  push_to_docker:
    needs: build_job
    name: push to dockerhub
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Image build and push
          run: gateway/build_and_push.sh
